function generateSampleAnswers() {
  return {
    useNewDir: "Yes, same as my Package Name",
    projectDir: "sample-package",
    useMonorepo: "No",
    monorepoRoot: ".",
    packageManager: "npm",
    publishTo: "Both",
    access: "public",
    createGitHubWorkflow: "Yes",
    createGitHubRepo: "No",
    ciProvider: "GitHub Actions",
    name: "sample-package",
    version: "0.0.1",
    moduleType: "CommonJS",
    githubUsername: "sampleuser",
    githubRepoName: "sample-package",
    githubToken: "NA",
    description: "A sample Node.js package",
    authorName: "Sample Author",
    authorEmail: "sample@example.com",
    authorUrl: "https://example.com",
    homepage: "https://example.com/sample-package",
    keywords: ["sample", "node", "package"],
    license: "MIT",
    useTypeScript: "No",
    useESLint: "No",
    usePrettier: "No",
    testFramework: "None",
    dependencies: {},
    devDependencies: {},
    customScripts: {},
  };
}

module.exports = { generateSampleAnswers };
